name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]


jobs:
  Test_on_x86:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        git submodule update --init --recursive
        python -m pip install --upgrade pip
        pip install faiss-cpu faiss-gpu
        sudo apt update
        sudo apt install nvidia-cuda-toolkit
        nvcc --version
        sudo wget -O /etc/apt/preferences.d/cuda-repository-pin-600 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
        sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
        sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
        sudo apt update
        sudo apt install cuda
        echo 'export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}' >> ~/.bashrc
        nvcc --version        
        cd faiss
        cmake -B build . -DFAISS_ENABLE_PYTHON=OFF
        make -C build -j8
        make -C build install
        cd ..
        pip install --no-binary :all: faiss-cpu
        export FAISS_ENABLE_GPU=ON
        export FAISS_LDFLAGS='-l:libfaiss.a -l:libopenblas.a -lgfortran -lcudart_static -lcublas_static -lculibos'
        pip install --no-binary :all: faiss-gpu
        export FAISS_OPT_LEVEL='avx2'
        export FAISS_LDFLAGS='-l:libfaiss_avx2.a -l:libopenblas.a -lgfortran'
        pip install --no-binary :all: faiss-cpu
        python setup.py install
        pip install pytest
    - name: Test with pytest
      run: |
        pytest
        python setup.py install
